### ISSUE TITLE
Segfault when the first token is a partial

### ISSUE THREAD

**Issue by gabstv** [benjamindblock/odin-mustache#3]
Hello,

First of all, thank you for this library. It is a great combo with the odin-http lib!

There seems to be a bug when the first token of a mustache template is a `{{> partial}}`.

The template below segfaults:

```mustache
{{> header}}
<h1>Hello, {{name}}!</h1>
{{> footer}}
```

If anything is added above the `{{> header}}` reference (even a line break), then it works:

```mustache
{{! hellope, to avoid the segfault }}
{{> header}}
<h1>Hello, {{name}}!</h1>
{{> footer}}
```

I'm new to Odin, otherwise I would open a PR to submit a fix for this.

**Comment by benjamindblock** [comment]
@gabstv -- Could you provide more specific repro steps? On the latest `main` branch, I don't encounter a segfault with the following arguments.

```
bin/odin-mustache tmp/repro.txt tmp/repro.json
```

`tmp/repro.txt`
```
{{> header}}
<h1>Hello, {{name}}!</h1>
{{> footer}}
```

`tmp/repro.json`
```
{
  "data": {
    "name": "Boris"
  },
  "partials": {
    "header": "BEGIN\n",
    "footer": "END"
  }
}
```

**Output**
```
BEGIN
<h1>Hello, Boris!</h1>
END
```

Thanks for using `odin-mustache`! Happy to have more people using it and reporting issues.
